version: '2'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=hackmd
      - POSTGRES_PASSWORD=hackmdpass
      - POSTGRES_DB=hackmd
  hackmd:
    build: ./hackmd
    ports:
      - "3000:3000"
    environment:
      - HMD_DB_URL=postgres://hackmd:hackmdpass@postgres:5432/hackmd
      - HMD_DOMAIN=localhost
      - HMD_ALLOW_ANONYMOUS=true
      - HMD_ALLOW_FREEURL=true
      - HMD_EMAIL=false
      - HMD_ALLOW_EMAIL_REGISTER=false
      - HMD_IMAGE_UPLOAD_TYPE=filesystem
