version: '2'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=hackmd
      - POSTGRES_PASSWORD=hackmdpass
      - POSTGRES_DB=hackmd
  hackmd:
    build: ./hackmd
    ports:
      - "3000:3000"
    environment:
      - HMD_DB_URL=postgres://hackmd:hackmdpass@postgres:5432/hackmd
      - HMD_DOMAIN=localhost
      - HMD_ALLOW_ANONYMOUS=true
      - HMD_ALLOW_FREEURL=true
      - HMD_EMAIL=false
      - HMD_ALLOW_EMAIL_REGISTER=false
      - HMD_IMAGE_UPLOAD_TYPE=filesystem
      #- HMD_LDAP_URL	ldap://example.com	url of LDAP server
      #- HMD_LDAP_BINDDN	no example	bindDn for LDAP access
      #- HMD_LDAP_BINDCREDENTIALS	no example	bindCredentials for LDAP access
      #- HMD_LDAP_TOKENSECRET	supersecretkey	secret used for generating access/refresh tokens
      #- HMD_LDAP_SEARCHBASE	o=users,dc=example,dc=com	LDAP directory to begin search from
      #- HMD_LDAP_SEARCHFILTER	(uid={{username}})	LDAP filter to search with
      #- HMD_LDAP_SEARCHATTRIBUTES	no example	LDAP attributes to search with
      #- HMD_LDAP_TLS_CA	no example	Root CA for LDAP TLS in PEM format
      #- HMD_LDAP_PROVIDERNAMEMy institution	Optional name to be displayed at login form indicating the LDAP provider
